app:
  url: "http://localhost:3000"

database:
  connection: mysql
  mysql:
    host: 127.0.0.1
    port: 3306
    database: gohub
    username: todo
    password: todo

mail:
  smtp:
    host: localhost
    port: 1025
    username:
    password:

  from:
    address: gohub@example.com
    name: Gohub

redis:
  host: 127.0.0.1
  port: 9000
  password:

sms:
  aliyun:
    access_key_id: todo
    access_key_secret: todo
    sign_name: todo
    template_code: todo