app:
  debug: true

database:
  connection: mysql
  mysql:
    master:
      host: 127.0.0.1
      port: 3306
      database: gohub
      username: root
      password: 123456
      charset: utf8mb4
    indexer:
      host: 127.0.0.1
      port: 3306
      database: indexer
      username: root
      password: 123456
      charset: utf8mb4

redis:
  host: 127.0.0.1
  port: 6379
  password:


file_base_path: storage/static/ # 文件存储路径

# 智能合约配置
eth:
  contract_address: 0xbCFB2b3aeEca7a535acd82a18BFa1a3013F09df5 # 合约地址
  rpc_url: http://127.0.0.1:8545 # rpc地址
  ws_rpc_url: ws://127.0.0.1:8545 # rpc ws 地址
  start_block: 70 # 合约部署块高度
  confirm_block: 0 # 确认块高度

mq:
  url: amqp://root:123456@localhost:5672/
